[RUN-96]  Update the logic of runic draws for individual rune description
dmowski/runar-ios pull request #110
Opened 2023-01-12 09:08 UTC by arti1233

Description 📝

Removed percent of luck in description of individual rune and replaced them with default phrases relevant lucky level.

---
Tests ✅

Simulator: iPhone SE gen 2 , 11, 14 Pro Max
Device : XR, iPhone 7

2023-01-12 10:14 UTC, Qeezii approved these changes

2023-01-12 13:10 UTC, Kengii approved these changes

2023-01-14 20:16 UTC, FilyutaDima commented
1) Task condition not met:

Issue: there are too often bad results with bad luckiness, we have bad rewies regading that 
To do: Update the logic of runic draws

2) The inscription does not fit in the label:

<img width="354" alt="Снимок экрана 2023-01-14 в 20 46 53" src="https://user-images.githubusercontent.com/23504718/212494551-461ef11b-4690-45d5-a0b3-d56df2b8af49.png">
<img width="352" alt="Снимок экрана 2023-01-14 в 20 37 04" src="https://user-images.githubusercontent.com/23504718/212494559-01bdc56f-ab03-4ba2-ae33-16153aa3ff3b.png">

2023-01-14 20:26 UTC, FilyutaDima commented
<img width="362" alt="Снимок экрана 2023-01-14 в 23 23 29" src="https://user-images.githubusercontent.com/23504718/212495066-e4154eaa-8b5b-46d1-b187-bacb64f7222e.png">
<img width="354" alt="Снимок экрана 2023-01-14 в 23 25 30" src="https://user-images.githubusercontent.com/23504718/212495091-5ba0bb95-be4c-41b7-87b9-fd1c62bf10fc.png">

2023-01-29 22:19 UTC, AliaksandrNiehaj requested changes

2023-01-29 22:19 UTC, AliaksandrNiehaj commented on Runar/Runar/Extensions/Int+Extension.swift
> +extension Int {
Please, think about more independent fix/decision.

2023-02-04 11:59 UTC, AliaksandrNiehaj approved these changes

2023-02-04 11:59 UTC, merged