Run 198
dmowski/runar-ios pull request #111
Opened 2023-01-14 14:15 UTC by Kengii

## Description 📝

Make the correct arrangement of elements on all types of screens in onboarding

---

### Tests ✅

Simulator: Iphone SE, 6s, SE gen 3, 8 Plus, 11 pro, 11 pro max, 14 pro

2023-01-14 17:07 UTC, Qeezii approved these changes

2023-01-14 17:07 UTC, FilyutaDima commented
Incorrect design of button "Start" on the Library screen. You have to change the background color and title color.

Current design:
<img width="288" alt="Снимок экрана 2023-01-14 в 19 10 03" src="https://user-images.githubusercontent.com/23504718/212485488-479c60eb-411f-4a6d-ae95-243f04846d4d.png">

Figma:
<img width="116" alt="Снимок экрана 2023-01-14 в 19 10 33" src="https://user-images.githubusercontent.com/23504718/212485597-5f2cb014-3f14-4f58-a776-b65e0dc2e284.png">

2023-01-15 14:30 UTC, arti1233 approved these changes

2023-01-17 20:00 UTC, FilyutaDima approved these changes

2023-01-29 22:17 UTC, AliaksandrNiehaj requested changes

2023-01-29 22:17 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +                make.leading.equalToSuperview().inset(64)
redundant line of code. Please, read the doc for SnapKit.

2023-01-29 22:17 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +                make.leading.equalToSuperview().inset(64)
Please, think about constants.

2023-01-29 22:17 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +                make.leading.equalToSuperview().inset(72)
Please, remove copy-paste.

2023-02-02 08:33 UTC, AliaksandrNiehaj requested changes

2023-02-02 08:33 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +        let fontConstant: CGFloat = DeviceType.iPhoneSE ? 24 : 30
Could you, please, explain, what does it mean: 6.58, 8, 0.82, 1?

2023-02-02 08:33 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +        onboardingStartButton.layer.borderColor = UIColor(red: 1, green: 0.917, blue: 0.792, alpha: 0.7).cgColor
Use, please, constants.

2023-02-02 08:33 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +        onboardingStartButton.setTitleColor(UIColor(red: 0.294, green: 0.282, blue: 0.259, alpha: 1), for: .normal)
The same (constants).

2023-02-02 08:33 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +            make.width.equalTo(264)
Fix hardcode, please

2023-02-02 08:33 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +            let factor: CGFloat = DeviceType.iPhoneSE ? 0.85 : 0.78
Could you, please, explain, what does it mean: 0.85, 0.78?

2023-02-04 12:14 UTC, AliaksandrNiehaj requested changes

2023-02-04 12:14 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +            let constant: CGFloat = DeviceType.iPhoneSE ? (viewWidth / 7.6) : (viewWidth / 5.45)
@Kengii what does it mean 7.6 and 5.45?
It looks like Kalashnikov machine gun cartridge calibers.

2023-02-04 12:14 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +            make.leading.equalToSuperview().inset(constant)
copy paste

2023-02-04 12:14 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenVC.swift
> +                contentView.onboardingNextSlideButton.isHidden = true
think, please, about ternary operator.

2023-02-04 12:14 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +            let factor: CGFloat = DeviceType.iPhoneSE ? 0.85 : 0.78
Fix, please, 0.85/0.78

2023-02-04 12:31 UTC, Kengii commented
SE
![SE](https://user-images.githubusercontent.com/97613101/216767625-126bd3a0-29ff-414c-a368-0f11ed2d634f.png)
SE 3
![SE 3](https://user-images.githubusercontent.com/97613101/216767648-fe917eb4-1681-4647-ac4f-c8676bcef0bb.png)
13 mini
![13 mini](https://user-images.githubusercontent.com/97613101/216767695-5f7d071b-fd8c-484e-a956-3222d84c0428.png)
8 plus
![8 Plus](https://user-images.githubusercontent.com/97613101/216767713-b4a0acfd-d9a5-4ebd-892c-ead39a3a6cbe.png)
X
![X](https://user-images.githubusercontent.com/97613101/216767739-4c9aa08d-7362-4189-a1cc-3d78052f9701.png)
14
![14](https://user-images.githubusercontent.com/97613101/216767768-89da189c-9652-49c1-9ea9-5e4eaf956dd2.png)
14 pro max
![14 pro max](https://user-images.githubusercontent.com/97613101/216767804-a9c07093-26f4-4562-bcaa-5bb1e65eb68f.png)

2023-02-05 12:08 UTC, AliaksandrNiehaj requested changes

2023-02-05 12:08 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +        onboardingStartButton.setTitleColor(UIColor(red: 0.825, green: 0.77, blue: 0.677, alpha: 1), for: .highlighted)
Use, please, introduced colors.

2023-02-05 12:08 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +        onboardingStartButton.setTitleColor(UIColor(red: 0.294, green: 0.282, blue: 0.259, alpha: 1), for: .normal)
Use, please, introduced colors.

2023-02-06 10:56 UTC, AliaksandrNiehaj approved these changes

2023-02-06 10:56 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +
Comment must be written above the var/let. Please, fix.

2023-02-06 10:56 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenCell.swift
> +            make.leading.equalToSuperview().inset(constantConstraintsDescription)
Copy paste.

2023-02-06 10:56 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingScreenVC.swift
> +                contentView.onboardingNextSlideButton.isHidden = true
?

2023-02-06 10:56 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/OnboardingScreen/OnboardingView.swift
> +    // this is a constant, a multiplier that is calculated from the screen dimensions, for the correct placement of the button on the screen
The same about comment.

2023-02-06 11:26 UTC, merged