RUN-317 Change the titles of Library section
dmowski/runar-ios pull request #114
Opened 2023-01-19 20:07 UTC by Kengii

## Description 📝

Change the titles of Library section

---

### Tests ✅

Simulator: Iphone SE, SE gen 3, 8 Plus, 11, 14 pro

2023-01-20 12:07 UTC, arti1233 commented on Runar/Runar/Controllers/Library flow/LibraryViewController.swift
>  public extension UINavigationBar {
Я бы сделал отдельный файл в папке Extensions и туда это все закинул

2023-01-20 12:07 UTC, arti1233 approved these changes

2023-01-24 16:07 UTC, Qeezii approved these changes

2023-01-28 09:09 UTC, FilyutaDima commented
- Check text color on titles of Library sections
- Remove background on titles of Library sections

Current:
<img width="346" alt="Снимок экрана 2023-01-28 в 12 01 30" src="https://user-images.githubusercontent.com/23504718/215257469-5f616d5f-ede1-4e80-950f-177bba0ca7a0.png">

Figma:
<img width="332" alt="Снимок экрана 2023-01-28 в 12 02 28" src="https://user-images.githubusercontent.com/23504718/215257505-665a5b33-c8e4-4821-bb71-597eed60962d.png">

2023-01-28 16:49 UTC, FilyutaDima approved these changes

2023-01-29 22:13 UTC, AliaksandrNiehaj requested changes
Please, think about more clean fix without copy-paste.

2023-02-02 08:28 UTC, AliaksandrNiehaj approved these changes

2023-02-02 08:28 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Library flow/LibraryViewController.swift
>  public extension UINavigationBar {
@arti1233 Please, use english in the future.

2023-02-02 08:28 UTC, merged