[RUN-297] Change the color of the indicator UITableView in LibraryNodeViewController
dmowski/runar-ios pull request #118
Opened 2023-01-29 14:15 UTC by Kengii

Description 📝

Changed the color of the indicator UITableView in LibraryNodeViewController

Tests ✅

Simulator: Iphone SE, 6s, SE gen 3, 8 Plus, 11 pro, 11 pro max, 14 pro

2023-01-29 22:09 UTC, AliaksandrNiehaj requested changes
Please, check the activity indicator configurations.

2023-02-02 08:20 UTC, AliaksandrNiehaj approved these changes

2023-02-02 11:08 UTC, arti1233 approved these changes

2023-02-03 16:29 UTC, Qeezii approved these changes

2023-02-04 15:52 UTC, SkrigalovskiAndrei approved these changes

2023-02-04 18:57 UTC, AliaksandrNiehaj approved these changes

2023-02-04 18:57 UTC, merged