[Run 291, 296, 320, 321]  Made the SettingsVC and AppInfoVC screen as in figma
dmowski/runar-ios pull request #120
Opened 2023-01-31 12:43 UTC by arti1233

Description  📝

Made the settings screen and the about app screen as in figma. Added clear navigation controller, title as in figma, added scroll on descriptions in AppInfoVC. 

---

Tests ✅

Simulator: iPhone SE gen 2 , 11, 14 Pro Max
Device : XR, iPhone 7

2023-02-01 14:35 UTC, Qeezii approved these changes

2023-02-01 19:05 UTC, Kengii commented
В фигме цвет у title navigation в settings другой
UIColor(red: 0.825, green: 0.77, blue: 0.677, alpha: 1)

2023-02-01 19:18 UTC, Kengii commented
iphone se 1gen not showing word back in navbar
Figma:
<img width="304" alt="Снимок экрана 2023-02-01 в 22 07 12" src="https://user-images.githubusercontent.com/97613101/216141261-9fb021c0-75cd-4a6e-951d-ab47de38dd7d.png">
Device:
<img width="304" alt="Снимок экрана 2023-02-01 в 22 06 39" src="https://user-images.githubusercontent.com/97613101/216141268-42ad0228-39dc-4b67-a91e-9c0a6fc4d47f.png">

2023-02-02 08:15 UTC, AliaksandrNiehaj requested changes

2023-02-02 08:15 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +        navigationVC.navigationBar.setBackgroundImage(UIImage(), for: .default)
Why do you use simple UIImage?

2023-02-02 08:18 UTC, AliaksandrNiehaj requested changes

2023-02-02 08:18 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Settings flow/AppInfoVC.swift
> +        paragraphStyle.lineHeightMultiple = 1.17
Lets use constants.

2023-02-02 08:18 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Settings flow/AppInfoVC.swift
> +        var attributedText = NSMutableAttributedString(string: string, attributes: [NSMutableAttributedString.Key.paragraphStyle: paragraphStyle,NSMutableAttributedString.Key.font: FontFamily.SFProDi
Lets create constant for Font and it later.

2023-02-02 08:18 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Settings flow/AppInfoVC.swift
> +            $0.leading.trailing.equalToSuperview().inset(24)
Use constants, please.

2023-02-02 08:18 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Settings flow/SettingsVC.swift
> +        navigationController?.navigationBar.titleTextAttributes = [NSAttributedString.Key.font: FontFamily.AmaticSC.bold.font(size: 36), NSAttributedString.Key.foregroundColor: UIColor(red: 0.825, gr
Need to use constant for color

2023-02-05 12:03 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +        navigationVC.navigationBar.setBackgroundImage(UIImage(), for: .default)
@arti1233 You still don't answered this question&

2023-02-05 12:04 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Settings flow/AppInfoVC.swift
> +        var attributedText = NSMutableAttributedString(string: string, attributes: [NSMutableAttributedString.Key.paragraphStyle: paragraphStyle,NSMutableAttributedString.Key.font: FontFamily.SFProDi
Moreover, use, please, short key values for attributed string.

2023-02-05 12:50 UTC, arti1233 commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +        navigationVC.navigationBar.setBackgroundImage(UIImage(), for: .default)
if i don't write this code on device with touch id appeared this grey view on the navigationBar 
![Simulator Screen Shot - iPhone 6s - 2023-02-05 at 15 49 54](https://user-images.githubusercontent.com/107428500/216819590-ea77b967-dda3-429c-97fd-84a00227d7f5.png)

2023-02-06 09:13 UTC, AliaksandrNiehaj approved these changes

2023-02-06 09:29 UTC, Kengii approved these changes

2023-02-06 11:27 UTC, merged