[RUN-277] - Generator flow design has changed
dmowski/runar-ios pull request #121
Opened 2023-02-01 15:05 UTC by FilyutaDima

## Description 📝

Generator flow design has changed

Updated the rune selection screen according to the design
Removed the text above rune selection (Собери свой руннй узор …..)
Updated titles on each page of the generator functionality

### Tests ✅

- iPhone 8, iPhone 11 Pro Max, iPhone 14 Pro Max - simulators
- iPhone 11 Pro Max - real device

2023-02-02 11:11 UTC, arti1233 approved these changes

2023-02-04 14:58 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Generator flow/SelectedRuneCell.swift
> -            runeName.topAnchor.constraint(equalTo: runeImage.bottomAnchor),
Double bottom?
Должно писать о конфликте

2023-02-04 15:00 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Generator flow/SelectionRuneVC.swift
> +
self здесь не нужен

2023-02-04 15:03 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Generator flow/WallpaperWithBackground/WallpaperWithBackgroundVC.swift
> -        title = .wallpapersHeader
extra self

2023-02-04 15:05 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +        super.init(effect: nil)
Старайся использовать weak вместо unowned

2023-02-04 15:08 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +
Property размещаются выше инициализатора

Использование "!" очень скользкая дорожка

2023-02-04 15:09 UTC, SkrigalovskiAndrei commented on Runar/Runar/Extensions/UINavigationController.swift
> +        titleLabel.text = title
extra self

2023-02-04 15:20 UTC, SkrigalovskiAndrei requested changes
Пофикси комментарии

2023-02-04 15:23 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Generator flow/SelectedRuneCell.swift
>              runeName.bottomAnchor.constraint(equalTo: bottomAnchor),
Double bottom?
Должно писать о конфликте

2023-02-04 15:24 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Generator flow/SelectionRuneVC.swift
> +        self.navigationItem.setNavigationTitle(.generateRunesTitle)
self здесь не нужен

2023-02-04 15:25 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Generator flow/WallpaperWithBackground/WallpaperWithBackgroundVC.swift
>          self.navigationItem.hidesBackButton = true
extra self

2023-02-04 15:25 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +        animator = UIViewPropertyAnimator(duration: 1, curve: .linear) { [unowned self] in self.effect = effect }
Старайся использовать weak вместо unowned

2023-02-04 15:25 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Misc/TabBarController/MainTabBarController.swift
> +    private var animator: UIViewPropertyAnimator!
Property размещаются выше инициализатора

Использование "!" очень скользкая дорожка

2023-02-04 15:26 UTC, SkrigalovskiAndrei commented on Runar/Runar/Extensions/UINavigationController.swift
> +        self.titleView = titleLabel
extra self

2023-02-04 19:12 UTC, Kengii commented
Simulator Iphone SE
1. Background NavBAr
![Simulator Screen Shot - Iphone SE - 2023-02-04 at 22 03 23](https://user-images.githubusercontent.com/97613101/216785287-1508a267-ad25-43d9-981b-3afd98cda80a.png)
2. wrong button names, check with figma
![Simulator Screen Shot - Iphone SE - 2023-02-04 at 22 04 54](https://user-images.githubusercontent.com/97613101/216785398-e284fbbe-f2c3-4843-aec0-cdfee53740ed.png)
![Simulator Screen Shot - Iphone SE - 2023-02-04 at 22 05 03](https://user-images.githubusercontent.com/97613101/216785405-59576f1c-3c0f-4f40-984a-313a59b0f070.png)
![Simulator Screen Shot - Iphone SE - 2023-02-04 at 22 05 18](https://user-images.githubusercontent.com/97613101/216785410-de230118-4f88-4ecc-95e2-694892087db4.png)

2023-02-06 15:36 UTC, AliaksandrNiehaj approved these changes

2023-02-06 15:44 UTC, SkrigalovskiAndrei approved these changes

2023-02-06 15:46 UTC, Qeezii approved these changes

2023-02-07 06:28 UTC, Kengii approved these changes

2023-02-07 17:43 UTC, merged