[RUN-318] Changed spacing between header and rune
dmowski/runar-ios pull request #125
Opened 2023-02-09 13:44 UTC by Kengii

## Description 📝

Changed spacing between header and rune, added constants.

---

### Test ✅

Simulator: SE, SE 3 gen, 8 plus, X, 14, 13 mini, 14 pro max

2023-02-09 16:31 UTC, SkrigalovskiAndrei commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +    static let runeDescBottomAnchor = -26.0
Avoid use negative numbers

2023-02-09 16:42 UTC, arti1233 approved these changes

2023-02-10 05:16 UTC, Qeezii approved these changes

2023-02-12 11:35 UTC, AliaksandrNiehaj requested changes

2023-02-12 11:35 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +    static let runeImageSize = CGSize(width: 109, height: 129)
Why do you use static size?

2023-02-12 11:35 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +            make.top.equalTo(safeAreaLayoutGuide).offset(CGFloat.runTitleTopAnchor)
Explain, please, why safeAreaLayoutGuide?

2023-02-12 11:35 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +            make.height.equalTo(CGFloat.runeTitleHeight)
You should avoid using types while using static var/let/func

2023-02-12 11:35 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +    static let tagsCVTopAnchor = 16.0
Please, explain, what is CV?

2023-02-12 11:35 UTC, AliaksandrNiehaj commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +    static let runeDescColor = UIColor(red: 0.855, green: 0.855, blue: 0.855, alpha: 1)
Could you, please, ask UI/UX team about this color?

2023-02-12 13:01 UTC, Kengii commented on Runar/Runar/Controllers/Library flow/LibraryCells/LibraryRuneCell.swift
> +    static let tagsCVTopAnchor = 16.0
Tags CollectionView

2023-02-12 15:30 UTC, SkrigalovskiAndrei approved these changes

2023-02-12 18:12 UTC, AliaksandrNiehaj approved these changes

2023-02-14 15:59 UTC, Qeezii approved these changes

2023-02-14 18:16 UTC, SkrigalovskiAndrei approved these changes

2023-02-14 20:41 UTC, FilyutaDima approved these changes

2023-03-04 20:11 UTC, Kengii commented
before: top anchor 26 
<img width="281" alt="Снимок экрана 2023-03-04 в 23 08 38" src="https://user-images.githubusercontent.com/97613101/222926636-1940ec7d-ded2-4d1d-bd4f-9c9ea0801b5c.png">
after: top anchor as in figma 15
<img width="281" alt="Снимок экрана 2023-03-04 в 23 09 06" src="https://user-images.githubusercontent.com/97613101/222926659-682215b4-45dd-47e5-a52b-e0b506aa2ca4.png">

2023-03-05 18:26 UTC, merged